### PR TITLE
Enhance SQL lexer

### PR DESCRIPTION
**Pull request by ThaiDat**
\* Remove "CASE" from keywords list. So that the whole CASE...WHEN... will be rendered as an expression. (Previously, CASE will be rendered differently as a Keyword)
\+ Add a lot more common keywords
\+ Add a lot more common built in functions

### CODE REVIEW

**Comment by ThaiDat** [comment]
@Alexey-T I will notify you here instead of creating a thread in CudaText repo. Please help review.

**Comment by Alexey-T** [comment]
Ok, here

**Review by Alexey-T — APPROVED** [review]

**Comment by Alexey-T** [comment]
can you add, pls, the similar fixes to 2 other lexers:

- SQL Blue
- SQL White

Screenshot from 2024-10-06 06-51-24

**Comment by ThaiDat** [comment]
What is the differences between these 3 lexers?

**Comment by Alexey-T** [comment]
They were created before Synwrite, by 3 different ppl. I don't remember the differences.

**Comment by Alexey-T** [comment]
If you tell me that 1-2 of these 3 , are outdated and not needed, I will remove them.

**Comment by ThaiDat** [comment]
I just think they should have some purposes to be there. If no, shouldn't waste effort to maintain 3 different code with the same purpose.

**Comment by Alexey-T** [comment]
maybe it's time to remove them.

**Comment by ThaiDat** [comment]
I just tested them. They are pretty outdated. They don't even support comments. But they have folding.
I think we can bring folding to SQL lexer and remove them.
image

**Comment by Alexey-T** [comment]
I remove them, tks.

**Pull request merged**
