### PR TITLE
Red lexer updates

### PR DESCRIPTION
**Pull request by hiiamboris**

### CODE REVIEW

**Comment by Alexey-T** [comment]
>    Expression = '\#[\w\d\-_]+'

`\w` includes `\d` in it. and also the '_'.

**Comment by Alexey-T** [comment]
2.

`Expression = '1\.\#(inf|nan)\b | ( (\d'#39'?)+`

note! lexer parser uses caseINSINSITIVE maths by default. is it OK for your 'inf' and 'nan'? if not, add the prefix to regex: `(?-i)`

**Comment by Alexey-T** [comment]
2b.

`Expression = '1\.\#(inf|nan)\b | ( (\d'#39'?)+`

i hope it is not error - you need to find `1.#inf` and `1.#nan` . or do we need only `#inf` and `#nan`?

**Comment by hiiamboris** [comment]
Thanks for reviewing. There's no formal specification of issue syntax yet, so I used a rough approximation that will make do for years hopefully.

> caseINSINSITIVE 

yes, that's how it should be

> i hope it is not error - you need to find 1.#inf and 1.#nan . or do we need only #inf and #nan?

correct forms are `1.#inf` and `1.#nan` (including all case variants), and yeah they look weird, but with lots of datatypes we have tight lexical space so sometimes tradeoffs like this are required :)

**Comment by hiiamboris** [comment]
https://github.com/red/docs/blob/master/en/datatypes/float.adoc but there's an error in that doc

**Comment by Alexey-T** [comment]
okay. last thing.

`      Expression = '\#[^/,\[\]\(\)\{\}"@:;\s]+'`

do you want to find all arithmetic operators here? star/ divide/ plus/ minus? and all emoji and CJK symbols?

**Comment by hiiamboris** [comment]
🤷🏻‍♀️ 
```
>> type? #/\-=+*?^
== issue!
```
Good catch on <> these don't work. Also despite `/` allowed Cuda treats it as a delimiter :/

**Comment by Alexey-T** [comment]
> despite / allowed Cuda treats it as a delimiter :/

how do you see that 'treat as delimeter'? do you run word-jump commands (goto word left/right)?
if so, correct the Cud option "nonword_chars" for Red lexer-config.

**Comment by Alexey-T** [comment]
i am applying the PR. about 'slash issue' - let's talk in differnt issue in the Cud repo? 
please write there - example long IDs which are highligted bad. and i will see.

**Comment by hiiamboris** [comment]
Sorry, I think it was my mistake. Late night lexing :)

**Pull request merged**
